### ISSUE TITLE
XML Reports not generated on Ubuntu

### ISSUE THREAD

**Issue by skycatch-teamcity** [ci-reporter/ci_reporter#152]
Hi
I've setup my rakefile and ruby test files using test/unit and ci_reporter on a mac OS platform - no problem. I can properly generate the XML reports from the unit tests using the command:
`rake ci:setup:testunit test`

However, when I cloned the same code to a ubuntu box, the tests run fine, but no XML report directory is created.
The output looks the same, as if it's creating the XML report directory defined by CI_REPORTS
<pre>
rm -rf test/reports
/usr/bin/ruby1.9.1 test/dummy_test.rb
Run options: 

# Running tests:

.

Finished tests in 0.001013s, 986.9496 tests/s, 986.9496 assertions/s.

1 tests, 1 assertions, 0 failures, 0 errors, 0 skips
</pre>
Any suggestions? I've seen some similiar posts online, but none of the suggested fixes are working for me. I'm running Ubuntu 14.04 with Ruby 1.9.3 and gems:
<pre>
ci_reporter (2.0.0)
ci_reporter_test_unit (1.0.0)
rake (10.3.2)
test-unit (2.5.5)
</pre>

Thanks
Michael

**Comment by shepmaster** [comment]
Is your code available somewhere so that we can use it to reproduce the issue? If not, could you create a reproducible example?

**Comment by skycatch-teamcity** [comment]
Thanks for responding. Here is my code:

Rakefile:
```
require 'rake'
require 'rake/testtask'

require 'rubygems'

gem 'ci_reporter_test_unit'
require 'ci/reporter/rake/test_unit'

ENV["CI_REPORTS"]  = "test/reports"

task :simpletest do
  create_TestTask(:simpletest, 'test/simple_test.rb')
end

def create_TestTask(name, pattern)
  Rake::TestTask.new do |tt|
    tt.name = name
    tt.libs <<< "test"
    tt.pattern = pattern
    tt.verbose = true
  end
end
```
Here is the simple_test.rb test file:
```
require 'rubygems'
require 'test/unit'

class SimpleTest < Test::Unit::TestCase

  def test_pass
    assert_equal(1,1)
  end

end
```

And the Command line:
```
$ rake ci:setup:testunit simpletest
rm -rf test/reports
/usr/bin/ruby1.9.1 -I"lib:test" -I"/var/lib/gems/1.9.1/gems/rake-10.3.2/lib" "/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/rake_test_loader.rb" "test/simple_test.rb"  /var/lib/gems/1.9.1/gems/ci_reporter_test_unit-1.0.0/lib/ci/reporter/rake/test_unit_loader.rb
Run options: 

# Running tests:

.

Finished tests in 0.000713s, 1403.4891 tests/s, 1403.4891 assertions/s.

1 tests, 1 assertions, 0 failures, 0 errors, 0 skips
```

This exact code properly creates the test/reports/ directory and associated .xml files when I run it on my Mac, but fails to create the reports on ubuntu

Any suggestions?

Thanks
Michael

**Comment by shepmaster** [comment]
Could you please try running your tests with `bundle exec`:

```
bundle exec rake ci:setup:testunit simpletest
```

Specifically, what I think is happening is that you are using the (very old) Test::Unit built into Ruby, which we don't support. When I ensure that I am using the gem, however, the run looks like:

```
$ bundle exec rake ci:setup:testunit simpletest
rm -rf test/reports
/usr/local/rvm/rubies/ruby-1.9.3-p551/bin/ruby -I"lib:test" -I"/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.3.2/lib" "/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.3.2/lib/rake/rake_test_loader.rb" "test/simple_test.rb"  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/ci_reporter_test_unit-1.0.0/lib/ci/reporter/rake/test_unit_loader.rb
Loaded suite /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.3.2/lib/rake/rake_test_loader
Started
.

Finished in 0.001061982 seconds.

1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

941.64 tests/s, 941.64 assertions/s
```

Note how the output is pretty different.

**Comment by shepmaster** [comment]
I assume that this resolved your problem.

**Comment by skycatch-teamcity** [comment]
Yes - that did - thank you. Sorry for the late response.
Can you confirm which minimum version of Test::Unit you require?

**Comment by shepmaster** [comment]
Like most gems, the gem spec specifies the version requirements:

https://github.com/ci-reporter/ci_reporter_test_unit/blob/94376edafdb48c671d6a8805df873e2985408b5f/ci_reporter_test_unit.gemspec#L20
