### ISSUE TITLE
Incompatibility with ruby 3.2.0 onwards

### ISSUE THREAD

**Issue by NotMyFault** [ci-reporter/ci_reporter#167]
Hey,

ruby 3.2.0 removed the `File.exists?` method, which was deprecated for years. The deprecation in ci_reporter has been addressed in 2014 in https://github.com/ci-reporter/ci_reporter/commit/2091680987059266d9c1f8108e2ff6f0135bb1cf, but there was no release since then.

This is a pretty useful tool, especially for Jenkins, if you want to aggregate test results. Unfortunately, I just had to drop this gem from one of our Jenkins gems https://github.com/jenkins-infra/asciidoctor-jenkins-extensions/pull/23, because of the incompatibility with ruby :/

@nicksieger and @shepmaster, would you be so kind and cut a release please, if you are still interested in maintaining this gem?
Alternatively, rubygems has an [adoption](https://blog.rubygems.org/2022/01/19/rubygems-adoptions.html) program, maintainers can submit their gems to, if they're looking for new maintainers.

Thanks in advance!

**Comment by nicksieger** [comment]
Please update to the new release version 2.1.0 and let me know how you go.
